keys:
  - &mewski age1rxem9nf4ey78fgnxuz0w298gf34my2qtdygkt52d258v9w20m3ysk66xtn
  - &zephyrus age1ryp5e29rqly3x5p9dugcrgf99fzp7kmggrw7ln43nc04gfpzhajqchum3c
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mewski
          - *zephyrus
