keys:
  - &user_mewski age1rxem9nf4ey78fgnxuz0w298gf34my2qtdygkt52d258v9w20m3ysk66xtn
  - &host_zephyrus age1ryp5e29rqly3x5p9dugcrgf99fzp7kmggrw7ln43nc04gfpzhajqchum3c
  - &host_crosshair age13qfyvrs38pjkp7sna0gn6y25r7lyk43p20mj95m50qglms8fd3eq3dg4a8
  - &host_astraeus age1n20kgfw65s77jyctjncjstydjfydvc0cqjrm7nf2kd2rsurp9vgs7ppck3

creation_rules:
  - path_regex: secrets/shared/.*\.yaml$
    key_groups:
      - age:
          - *user_mewski
          - *host_zephyrus
          - *host_crosshair
          - *host_astraeus

  - path_regex: secrets/zephyrus/.*\.yaml$
    key_groups:
      - age:
          - *user_mewski
          - *host_zephyrus

  - path_regex: secrets/crosshair/.*\.yaml$
    key_groups:
      - age:
          - *user_mewski
          - *host_crosshair

  - path_regex: secrets/astraeus/.*\.yaml$
    key_groups:
      - age:
          - *user_mewski
          - *host_astraeus
