keys:
  - &zephyrus age1ryp5e29rqly3x5p9dugcrgf99fzp7kmggrw7ln43nc04gfpzhajqchum3c

creation_rules:
  - path_regex: mewski-secrets/common\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *zephyrus

  - path_regex: mewski-secrets/zephyrus\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *zephyrus
