keys:
  - &mewski age1rxem9nf4ey78fgnxuz0w298gf34my2qtdygkt52d258v9w20m3ysk66xtn
  # - &zephyrus age1rgffpespcyjn0d8jglk7km9kfrfhdyev6camd3rck6pn8y47ze4sug23v3
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mewski
          # - *zephyrus
  - path_regex: secrets/zephyrus/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
          - *mewski
          # - *zephyrus
