{
  perSystem =
    { pkgs, ... }:
    {
      devShells = {
        security = pkgs.mkShell {
          packages = [
            (pkgs.python3.withPackages (
              ps: with ps; [
                # angr
                capstone
                evtx
                fickling
                gmpy2
                impacket
                keystone-engine
                pefile
                pycryptodome
                pwntools
                ropgadget
                ropper
                scapy
                unicorn
                z3-solver
              ]
            ))
          ]
          ++ (with pkgs; [
            pwndbg
            adidnsdump
            aircrack-ng
            amass
            apktool
            aria2
            arjun
            arp-scan
            autopsy
            bandwhich
            bettercap
            bloodhound
            bloodhound-py
            bulk_extractor
            bully
            burpsuite
            cadaver
            certipy
            chisel
            coercer
            commix
            crowbar
            crunch
            cewl
            cutter
            dalfox
            davtest
            dex2jar
            dnsrecon
            dnsx
            doggo
            enum4linux
            enum4linux-ng
            ettercap
            evil-winrm
            exploitdb
            eyewitness
            fcrackzip
            feroxbuster
            ffuf
            fierce
            foremost
            fping
            freerdp
            frida-tools
            gau
            gitleaks
            gobuster
            gowitness
            haiti
            hakrawler
            hash-identifier
            hashcat
            hashcat-utils
            hcxdumptool
            hcxtools
            httpx
            iaito
            inetutils
            iperf3
            ipmitool
            jadx
            john
            joomscan
            jwt-cli
            katana
            kerbrute
            laudanum
            ldeep
            lftp
            libseccomp
            ligolo-ng
            lldb
            macchanger
            mariadb
            massdns
            masscan
            medusa
            metasploit
            mimikatz
            # mitmproxy
            mtr
            nbtscan
            net-snmp
            netdiscover
            netexec
            nikto
            nuclei
            one_gadget
            onesixtyone
            openvpn
            parsero
            pdfcrack
            pdfrip
            pixiewps
            powershell
            proxychains-ng
            radare2
            rdesktop
            reaverwps-t6x
            recon-ng
            redis
            remmina
            responder
            rizin
            rlwrap
            rustscan
            sage
            samba
            seclists
            sherlock
            sleuthkit
            smbmap
            smtp-user-enum
            social-engineer-toolkit
            sqlmap
            sshpass
            sshuttle
            starkiller
            steghide
            stegsolve
            step-cli
            subfinder
            testdisk
            testssl
            thc-hydra
            theharvester
            tigervnc
            tor
            torsocks
            trippy
            trufflehog
            upx
            volatility3
            vt-cli
            wafw00f
            waybackurls
            whatweb
            whois
            wifite2
            wireguard-tools
            wpscan
            xh
            xxd
            yara
            zsteg
          ]);

          SECLISTS = "${pkgs.seclists}/share/wordlists/seclists";
        };
      };
    };

}
