{ inputs, ... }:

{
  imports = [
    # Hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix

    # System power management features
    ./power.nix

    # Host-specific system package overrides
    ./system-overrides.nix

    # Hardware support modules
    ../../modules/nixos/hardware/bluetooth.nix
    ../../modules/nixos/hardware/nvidia.nix

    # Secure boot configuration
    ../../modules/nixos/bootloader/lanzaboote.nix

    # ASUS Zephyrus G16 (2024) specific hardware optimizations
    inputs.nixos-hardware.nixosModules.asus-zephyrus-gu605my
  ];
}
