{ self, ... }:
{
  flake.nixosModules.security = {
    home-manager.sharedModules = [ self.homeModules.security ];
  };

  flake.homeModules.security =
    { pkgs, ... }:
    {
      imports = [
        self.homeModules.binary-ninja
      ];

      home = {
        file.".local/share/seclists".source = "${pkgs.seclists}/share/wordlists/seclists";

        packages = with pkgs; [
          cutter
          ghidra
          iaito
          radare2
          binwalk
          checksec
          wabt
          gdb
          lldb
          ltrace
          strace
          valgrind
          pwndbg
          pwndbg-lldb
          one_gadget
          wireshark-cli
          tcpdump
          nmap
          masscan
          rustscan
          trippy
          bandwhich
          dogdns
          aria2
          burpsuite
          ffuf
          feroxbuster
          gobuster
          nikto
          sqlmap
          wpscan
          joomscan
          arjun
          commix
          nuclei
          mitmproxy
          amass
          subfinder
          dnsrecon
          dnsutils
          dnsx
          fierce
          theharvester
          recon-ng
          sherlock
          massdns
          eyewitness
          gowitness
          httpx
          gau
          waybackurls
          whatweb
          parsero
          trufflehog
          gitleaks
          testssl
          hashcat
          hashcat-utils
          john
          thc-hydra
          medusa
          crowbar
          crunch
          cewl
          aircrack-ng
          wifite2
          bully
          reaverwps-t6x
          hcxdumptool
          hcxtools
          pixiewps
          metasploit
          social-engineer-toolkit
          exploitdb
          laudanum
          chisel
          ligolo-ng
          sshuttle
          proxychains-ng
          bloodhound
          mimikatz
          evil-winrm
          powershell
          certipy
          netexec
          kerbrute
          adidnsdump
          coercer
          starkiller
          smbmap
          enum4linux-ng
          bettercap
          ettercap
          macchanger
          netcat-gnu
          socat
          inetutils
          ipmitool
          nbtscan
          net-snmp
          smtp-user-enum
          onesixtyone
          freerdp
          remmina
          tigervnc
          openvpn
          wireguard-tools
          tor
          torsocks
          sshpass
          sleuthkit
          volatility3
          testdisk
          foremost
          bulk_extractor
          autopsy
          dc3dd
          steghide
          stegsolve
          zsteg
          exiftool
          step-cli
          jwt-cli
          cadaver
          davtest
          lftp
          libseccomp
          mariadb
          pdfrip
          redis
          responder
          sage
          seclists
          vt-cli
          whois
          yara
        ];
      };
    };
}
