{ self, ... }:
{
  flake.nixosModules.security = {
    home-manager.sharedModules = [ self.homeModules.security ];
  };

  flake.homeModules.security =
    { pkgs, ... }:
    {
      imports = [
        self.homeModules.binary-ninja
      ];

      home = {
        file.".local/share/seclists".source = "${pkgs.seclists}/share/wordlists/seclists";

        packages = with pkgs; [
          adidnsdump
          aircrack-ng
          amass
          android-tools
          apktool
          aria2
          arjun
          arp-scan
          autopsy
          bandwhich
          bettercap
          binutils
          binwalk
          bloodhound
          bloodhound-py
          bulk_extractor
          bully
          burpsuite
          cadaver
          certipy
          # checksec  # provided by python3 env (via pwntools)
          chisel
          coercer
          commix
          crowbar
          crunch
          cewl
          cutter
          dalfox
          davtest
          dex2jar
          dnsrecon
          dnsutils
          dnsx
          doggo
          elfutils
          enum4linux
          enum4linux-ng
          ettercap
          evil-winrm
          exiftool
          exploitdb
          eyewitness
          fcrackzip
          feroxbuster
          ffuf
          fierce
          file
          foremost
          fping
          freerdp
          frida-tools
          gau
          gdb
          ghidra
          gitleaks
          gobuster
          gowitness
          haiti
          hakrawler
          hash-identifier
          hashcat
          hashcat-utils
          hcxdumptool
          hcxtools
          httpie
          httpx
          iaito
          inetutils
          iperf3
          ipmitool
          jadx
          john
          joomscan
          jwt-cli
          katana
          kerbrute
          laudanum
          ldeep
          lftp
          libseccomp
          ligolo-ng
          lldb
          ltrace
          macchanger
          mariadb
          massdns
          masscan
          medusa
          metasploit
          mimikatz
          mitmproxy
          mtr
          nasm
          nbtscan
          net-snmp
          netcat-gnu
          netdiscover
          netexec
          nikto
          nmap
          nuclei
          one_gadget
          onesixtyone
          openvpn
          parsero
          patchelf
          pdfcrack
          pdfrip
          pixiewps
          powershell
          proxychains-ng
          radare2
          rdesktop
          reaverwps-t6x
          recon-ng
          redis
          remmina
          responder
          rizin
          rlwrap
          rustscan
          sage
          samba
          seclists
          sherlock
          sleuthkit
          smbmap
          smtp-user-enum
          social-engineer-toolkit
          socat
          sqlmap
          sshpass
          sshuttle
          starkiller
          steghide
          stegsolve
          step-cli
          strace
          subfinder
          tcpdump
          testdisk
          testssl
          thc-hydra
          theharvester
          tigervnc
          tor
          torsocks
          trippy
          trufflehog
          upx
          valgrind
          volatility3
          vt-cli
          wabt
          wafw00f
          waybackurls
          whatweb
          whois
          wifite2
          wireguard-tools
          wireshark-cli
          # wordlists
          wpscan
          xh
          xxd
          yara
          zsteg
        ];
      };
    };
}
