{ self, ... }:
{
  flake.nixosModules.security = {
    home-manager.sharedModules = [ self.homeModules.security ];
  };

  flake.homeModules.security =
    { pkgs, ... }:
    {
      imports = [
        self.homeModules.binary-ninja
      ];

      home = {
        file.".local/share/seclists".source = "${pkgs.seclists}/share/wordlists/seclists";

        packages = with pkgs; [
          aircrack-ng
          amass
          angr-management
          arjun
          bettercap
          binwalk
          bloodhound
          bully
          burpsuite
          cadaver
          certipy
          cewl
          chisel
          commix
          crowbar
          crunch
          davtest
          dnsrecon
          dnsutils
          dnsx
          enum4linux-ng
          ettercap
          evil-winrm
          exiftool
          exploitdb
          eyewitness
          feroxbuster
          ffuf
          fierce
          foremost
          freerdp
          gau
          gdb
          ghidra
          gobuster
          gowitness
          hashcat
          hashcat-utils
          hcxdumptool
          hcxtools
          httpx
          inetutils
          ipmitool
          john
          joomscan
          jwt-cli
          kerbrute
          laudanum
          lftp
          libseccomp
          ligolo-ng
          lldb
          ltrace
          macchanger
          mariadb
          massdns
          masscan
          medusa
          metasploit
          mimikatz
          mitmproxy
          nbtscan
          net-snmp
          netcat-gnu
          netexec
          nikto
          nmap
          nuclei
          one_gadget
          onesixtyone
          openvpn
          parsero
          pixiewps
          powershell
          proxychains-ng
          pwndbg
          pwndbg-lldb
          radare2
          reaverwps-t6x
          recon-ng
          redis
          remmina
          responder
          rustscan
          sage
          seclists
          sherlock
          sleuthkit
          smbmap
          smtp-user-enum
          socat
          social-engineer-toolkit
          sqlmap
          sshpass
          starkiller
          stegsolve
          steghide
          step-cli
          strace
          subfinder
          tcpdump
          testdisk
          thc-hydra
          theharvester
          tigervnc
          tor
          torsocks
          valgrind
          volatility3
          vt-cli
          wabt
          waybackurls
          wfuzz
          whatweb
          whois
          wifite2
          wireshark-cli
          wireguard-tools
          wpscan
          yara
          zsteg
        ];
      };
    };
}
